### PR TITLE
Prevent listener leaks, closes #67

### LINKED ISSUE #67: Test File Server leaking event listeners
Noticed that when I was working on the test file server and it was getting reloaded multiple times, that I'd get this error:

```
[orchestrator] show GraphQL dashboard via: http://localhost:24002
[test files] test files updated
[test files] test files updated
[test files] test files updated
[test files] test files updated
[test files] test files updated
[test files] test files updated
[test files] test files updated
[test files] test files updated
[test files] test files updated
(node:60268) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit
```

### PR DESCRIPTION
**Pull request by jnicklas**
Essentially this reverts `watch` to work more like it did before, where it only ever creates *one* listener, thus preventing leaks. 

I'm honestly not too sure why the listeners were leaking in the other implementation, I think it shouldn't be happening, but it might be some combination of this implementation using monitor and `on` together?

At any rate, this implementation is probably more performant, and easier to reason about, since we're not attaching and removing listeners all the time.

The downside is that we have to use `ensure` to get rid of the listener. We could use a monitor, but that seems like a bit on an anti pattern to me. We definitely want the detachment of the listener to be synchronous with shut-down of the Execution, so I think using ensure is better.

### CODE REVIEW

File: src/effection/events.ts [hunk 1]
```diff
@@ -25,14 +25,21 @@ export function watch(
...
     for(let name of [].concat(names)) {
-      let context = parent as any; // eslint-disable-line @typescript-eslint/no-explicit-any
-      context.spawn(monitor(function*() {
-        while (true) {
-          let args = yield on(emitter, name);
-          yield send(prepare.apply({ event: name}, args), parent);
-        }
-      }));
+      let listener = (...args) => {
+        parentContext.spawn(fork(function*() {
```
Comment (cowboyd) [inline src/effection/events.ts]: We don't have to wrap this operation in a generator here:

```ts
let deliverMessage = fork(send(prepare.apply({ event: name}, args), parentContext))
parentContext.spawn(deliverMessage);
```
Would also work.

Comment (jnicklas) [reply src/effection/events.ts]: Neat :)
